name: Publish to Figma store

on:
  push:
    branches: [ "main" ]

env:
  FIGMA_WEB_AUTHN_TOKEN: ${{ secrets.FIGMA_WEB_AUTHN_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install


    - name: Build plugin
      run: |
        npm run build

    - name: Set next Figma version as Figma version in package.json
      run: |
        node scripts/prepare.js

    # - name: Publish new Version to Figma
    #   run: |
    #     npx figcd release
